---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
     matchLabels:
       app: swiggy
     template:
        metadata:
          labels:
            app: swiggy
      spec:
        containers:
          - name: cont1
            image: shaikmustafa/dm
            ports:
              - containerPort: 80
    
